export { default as Author } from "./Author";
export { default as EpigraphPoetry } from "./EpigraphPoetry";
export { default as EpigraphProse } from "./EpigraphProse";
export { default as Heading1 } from "./Heading1";
export { default as Heading2 } from "./Heading2";
export { default as Heading3 } from "./Heading3";
export { default as Plain } from "./Plain";
export { default as Title } from "./Title";
export { default as Subtitle } from "./Subtitle";
